server:
  port: 9101

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      encoding: UTF-8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com:
      guner: DEBUG



single-sender:
  queue:
    name:
      single-queue: single-queue
  topic-exchange:
    name: single-exchange
  routing:
    key:
      single-routing: single-routing